# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ActuatorUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 481)
        MainWindow.setMinimumSize(QtCore.QSize(750, 464))
        MainWindow.setStyleSheet("QScrollBar\n"
"{\n"
"    width: 20px;\n"
"    border:none;\n"
"    border-radius: 10px;\n"
"    background: #32323C;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page \n"
"{\n"
"    background-color: #32323C;\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line \n"
"{\n"
"    background-color: #32323C;\n"
"}\n"
"QScrollBar::handle\n"
"{\n"
"    background-color: grey;\n"
"    min-height: 30px;\n"
"    border-radius: 10px;\n"
"    border:none;\n"
"}\n"
"QScrollBar::up-arrow\n"
"{\n"
"    background: none;\n"
"}\n"
"QScrollBar::down-arrow\n"
"{\n"
"    background: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loading = QtWidgets.QFrame(self.centralwidget)
        self.loading.setObjectName("loading")
        self.loading_screen = QtWidgets.QVBoxLayout(self.loading)
        self.loading_screen.setObjectName("loading_screen")
        self.textBrowser = QtWidgets.QTextBrowser(self.loading)
        self.textBrowser.setStyleSheet("/*General Styling*/\n"
"* {\n"
"  \n"
"  font: 10pt \"Roboto \";\n"
"  font-size: 14px;\n"
"  background-color: #32323C;\n"
"  color: #FFFFFF;\n"
"}\n"
"\n"
"/*Text Box Styling*/\n"
"QTextBrowser {\n"
"  border: none; \n"
"  padding-left:10px; \n"
"  padding-top:10px;\n"
"  border-radius: 10px;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.loading_screen.addWidget(self.textBrowser)
        self.progressBar = QtWidgets.QProgressBar(self.loading)
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"    border: solid grey;\n"
"    border-radius: 15px;\n"
"    color: black;\n"
"}\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #00f0c3;\n"
"    border-radius:15px;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.loading_screen.addWidget(self.progressBar)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.loading_screen.addItem(spacerItem)
        self.verticalLayout.addWidget(self.loading)
        self.options_widget = QtWidgets.QWidget(self.centralwidget)
        self.options_widget.setObjectName("options_widget")
        self.options = QtWidgets.QHBoxLayout(self.options_widget)
        self.options.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.options.setObjectName("options")
        self.name = QtWidgets.QLineEdit(self.options_widget)
        self.name.setObjectName("name")
        self.options.addWidget(self.name)
        self.pin = QtWidgets.QLineEdit(self.options_widget)
        self.pin.setObjectName("pin")
        self.options.addWidget(self.pin)
        self.min = QtWidgets.QLineEdit(self.options_widget)
        self.min.setObjectName("min")
        self.options.addWidget(self.min)
        self.max = QtWidgets.QLineEdit(self.options_widget)
        self.max.setObjectName("max")
        self.options.addWidget(self.max)
        self.add = QtWidgets.QPushButton(self.options_widget)
        self.add.setObjectName("add")
        self.options.addWidget(self.add)
        self.verticalLayout.addWidget(self.options_widget)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 730, 70))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.name_1.setMinimumSize(QtCore.QSize(100, 50))
        self.name_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.name_1.setObjectName("name_1")
        self.horizontalLayout_2.addWidget(self.name_1)
        self.value = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.value.setOrientation(QtCore.Qt.Horizontal)
        self.value.setObjectName("value")
        self.horizontalLayout_2.addWidget(self.value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.upload = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload.sizePolicy().hasHeightForWidth())
        self.upload.setSizePolicy(sizePolicy)
        self.upload.setMaximumSize(QtCore.QSize(150, 16777215))
        self.upload.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.upload.setObjectName("upload")
        self.horizontalLayout_6.addWidget(self.upload)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setMinimumSize(QtCore.QSize(0, 50))
        self.logo.setStyleSheet("QLabel#logo{\n"
"  background-color: #32323C;\n"
"  image: url(Ui/SideKick_Logo.png);\n"
"  width:100px;\n"
"  height:50px;\n"
"}\n"
"")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.horizontalLayout_6.addWidget(self.logo)
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Actuator Test"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto \'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Uploading sketch please wait</span></p></body></html>"))
        self.add.setText(_translate("MainWindow", "Add Actuator"))
        self.name_1.setText(_translate("MainWindow", "   All   "))
        self.upload.setText(_translate("MainWindow", "Upload Tester"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
