# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\NewActuatorUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(447, 201)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 427, 161))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.min = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.min.setObjectName("min")
        self.horizontalLayout.addWidget(self.min)
        self.add = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add)
        self.name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.pin = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.pin.setObjectName("pin")
        self.horizontalLayout.addWidget(self.pin)
        self.max = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.max.setObjectName("max")
        self.horizontalLayout.addWidget(self.max)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.name_1.setMinimumSize(QtCore.QSize(30, 0))
        self.name_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.name_1.setObjectName("name_1")
        self.horizontalLayout_2.addWidget(self.name_1)
        self.value = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.value.setOrientation(QtCore.Qt.Horizontal)
        self.value.setObjectName("value")
        self.horizontalLayout_2.addWidget(self.value)
        self.pos_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.pos_1.setMinimumSize(QtCore.QSize(50, 0))
        self.pos_1.setText("")
        self.pos_1.setObjectName("pos_1")
        self.horizontalLayout_2.addWidget(self.pos_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Actuator Test"))
        self.add.setText(_translate("MainWindow", "Add Actuator"))
        self.name_1.setText(_translate("MainWindow", "   All   "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
