name: Pylint

on:
  push:
    branches:    
      - '*'
  pull_request:
    branches: [ "main" ]
  

jobs:
  pylint:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Setup python to check the code agaist pylint
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt

    # Test all of the GUI files
    - name: Analysing main.py
      run: |
        pylint main.py --disable=E1136,R1725,R0902,R0904,E0611
        
    - name: Analysing file_manager.py
      run: |
        pylint file_manager.py --disable=R0902,R1725,R0904
        
    - name: Analysing message_handler.py
      run: |
        pylint message_handler.py --disable=R0902
        
    - name: Analysing device_manager.py
      run: |
        pylint device_manager.py --disable=R0902,R1732
        
    - name: Analysing widgets.py
      run: |
        pylint widgets.py --disable=R0903,C0103
        
    - name: Analysing library.py
      run: |
        pylint library.py --disable=R1732

    - name: Analysing boards.py
      run: |
        pylint boards.py

    - name: Analysing actuator.py
      run: |
        pylint actuator.py --disable=R0903

    - name: Analysing cli_manager.py
      run: |
        pylint cli_manager.py

    - name: Analysing terminal_manager.py
      run: |
        pylint terminal_manager.py

    - name: Analysing manager.py
      run: |
        pylint manager.py --disable=R0913,C0103,R0902

    - name: Analysing globals.py
      run: |
        pylint globals.py

    # Test all of the testing files
    - name: Analysing test_gui.py
      run: |
        pylint ./Testing/test_gui.py