name: Pylint

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt

    - name: Analysing main.py
      run: |
        pylint main.py --disable=I1101,E1136,R1725,R0902,R0904,E0611 --extension-pkg-whitelist=<PyQt5,PyQt5.QtWidgets,PyQt5.QtGui>
        
    - name: Analysing file_manager.py
      run: |
        pylint file_manager.py --disable=R0902,R1725
        
    - name: Analysing message_handler.py
      run: |
        pylint message_handler.py --disable=R0902
        
    - name: Analysing device_manager.py
      run: |
        pylint device_manager.py --disable=R0902,R1732
        
    - name: Analysing widgets.py
      run: |
        pylint widgets.py --disable=R0903,I1101
        
    - name: Analysing library.py
      run: |
        pylint library.py --disable=I1101,R1732 --extension-pkg-whitelist=<PyQt5,PyQt5.QtWidgets,PyQt5.QtGui>

    - name: Analysing actuator.py
      run: |
        pylint actuator.py --disable=I1101,R0903 --extension-pkg-whitelist=<PyQt5,PyQt5.QtWidgets,PyQt5.QtGui>

    - name: Analysing cli_manager.py
      run: |
        pylint cli_manager.py --extension-pkg-whitelist=<PyQt5,PyQt5.QtWidgets,PyQt5.QtGui>
